#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
// RUST-1 Electron renderer proof driver, through the sanctioned VisualQaRunner
// (single Electron process, lock, launch cap, leak check).
//
//   node spikes/rust-1-wasm-boundary/build.mjs
//   node spikes/rust-1-wasm-boundary/electron/run.cjs
//
// Writes out/electron-proof.json. Exit 0 only if the production-CSP page
// loads the wasm and passes every check, and the negative-control page (CSP
// minus 'wasm-unsafe-eval') is blocked.
'use strict';
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { VisualQaRunner } = require('../../../qa/visual-qa/runner');
const { acquire } = require('../../../qa/visual-qa/lock');

const HERE = __dirname;
const SPIKE = path.join(HERE, '..');
const ROOT = path.join(SPIKE, '..', '..');
const OUT = path.join(SPIKE, 'out');

// 1. CSP identity: proof.html must carry editor.html's CSP byte-for-byte.
const cspOf = (file) => {
  const m = /<meta http-equiv="Content-Security-Policy" content="([\s\S]*?)">/.exec(fs.readFileSync(file, 'utf8'));
  if (!m) throw new Error(`no CSP in ${file}`);
  return m[1];
};
const prodCsp = cspOf(path.join(ROOT, 'renderer/editor.html'));
const proofCsp = cspOf(path.join(HERE, 'proof.html'));
const negCsp = cspOf(path.join(HERE, 'proof-no-wasm-eval.html'));
if (proofCsp !== prodCsp) { console.error('proof.html CSP differs from renderer/editor.html'); process.exit(2); }
if (negCsp !== prodCsp.replace(" 'wasm-unsafe-eval'", '') || negCsp === prodCsp) {
  console.error('negative-control CSP is not editor.html minus wasm-unsafe-eval'); process.exit(2);
}

// 2. Generated modules: the wasm bytes (embedded loader) and the perf inputs.
const pkg = path.join(OUT, 'pkg');
if (!fs.existsSync(path.join(pkg, 'wrlforge_wasm_bg.wasm'))) { console.error('run build.mjs first'); process.exit(2); }
fs.mkdirSync(path.join(OUT, 'electron'), { recursive: true });
const wasm = fs.readFileSync(path.join(pkg, 'wrlforge_wasm_bg.wasm'));
fs.writeFileSync(path.join(OUT, 'electron', 'wasm-bytes.mjs'),
  `// generated by run.cjs from out/pkg/wrlforge_wasm_bg.wasm\nexport const WASM_BYTES = Uint8Array.from(atob('${wasm.toString('base64')}'), (c) => c.charCodeAt(0));\n`);
(async () => {
  const { loadInputs } = await import('../perf/inputs.mjs');
  const inputs = loadInputs(ROOT);
  fs.writeFileSync(path.join(OUT, 'electron', 'perf-inputs.mjs'),
    `// generated by run.cjs\nexport const INPUTS = ${JSON.stringify(inputs)};\n`);

  const electronBinary = require('electron');
  const runner = new VisualQaRunner({
    spawn: () => spawn(electronBinary, [path.join(HERE, 'main.cjs')], { cwd: ROOT, stdio: ['pipe', 'pipe', 'inherit'] }),
    log: (rec) => process.stderr.write(JSON.stringify(rec) + '\n'),
    maxLaunches: 1,
    retriesPerLaunch: 0,
    captureTimeoutMs: 180000,
  });
  const release = acquire();
  let results;
  let failure = null;
  try {
    results = await runner.run([
      { id: 'production-csp', page: 'proof.html' },
      { id: 'no-wasm-eval-csp', page: 'proof-no-wasm-eval.html' },
    ]);
  } catch (e) {
    failure = String(e.message || e);
  } finally {
    release();
  }
  const survivors = runner.survivors();
  const out = { failure, survivors, cspIdenticalToEditorHtml: true, results };
  fs.writeFileSync(path.join(OUT, 'electron-proof.json'), JSON.stringify(out, null, 2) + '\n');
  if (failure || survivors.length) { console.error(failure, survivors); process.exit(1); }
  const prod = results.find((r) => r.id === 'production-csp');
  const neg = results.find((r) => r.id === 'no-wasm-eval-csp');
  const prodOk = !prod.fatal && Object.values(prod.loaders).some((l) => l.ok) && prod.checks.length > 0 && prod.checks.every((c) => c.ok);
  const negBlocked = Object.values(neg.loaders).every((l) => !l.ok);
  const brief = (r) => ({ page: r.page, electron: r.electron, chrome: r.chrome, webPreferences: r.webPreferences, env: { ...r.env, userAgent: undefined },
    evalBlocked: r.evalBlocked, cspViolations: r.cspViolations, loaders: r.loaders, checks: r.checks.map((c) => `${c.ok ? 'PASS' : 'FAIL'} ${c.name}${c.detail ? ` (${c.detail})` : ''}`), fatal: r.fatal });
  console.log(JSON.stringify({ prodOk, negBlocked, production: brief(prod), negative: brief(neg) }, null, 2));
  process.exit(prodOk && negBlocked ? 0 : 1);
})();
